import { Category } from "../../types";
import { expenseTypes, categoryTypes } from "../costants";

export const defaultCategories: Category[] = [
  {
    id: 1,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "groceries",
    caption: "Groceries",
    color: "#0de2a3",
  },
  {
    id: 2,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[1].id,
    value: "shopping",
    caption: "Shopping",
    color: "#75effd",
  },
  {
    id: 3,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[1].id,
    value: "restaurants",
    caption: "Restaurants",
    color: "#c4db8e",
  },
  {
    id: 4,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "transport",
    caption: "Transport",
    color: "#244c55",
  },
  {
    id: 5,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[1].id,
    value: "travel",
    caption: "Travel",
    color: "#b8fcfa",
  },
  {
    id: 6,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[1].id,
    value: "entertainment",
    caption: "Entertainment",
    color: "#f3edbe",
  },
  {
    id: 7,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "utilities",
    caption: "Utilities",
    color: "#ce297a",
  },
  {
    id: 8,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "health",
    caption: "Health",
    color: "#675679",
  },
  {
    id: 9,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "services",
    caption: "Services",
    color: "#49c4eb",
  },
  {
    id: 10,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "transfers",
    caption: "Transfers",
    color: "#07efc2",
  },
  {
    id: 11,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "cash",
    caption: "Cash",
    color: "#8f82f3",
  },
  {
    id: 12,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[1].id,
    value: "general",
    caption: "General",
    color: "#4dd694",
  },
  {
    id: 13,
    expenseType: expenseTypes[0].id,
    budgetType: categoryTypes[0].id,
    value: "insurance",
    caption: "Insurance",
    color: "#efb1385",
  },
  {
    id: 14,
    expenseType: expenseTypes[1].id,
    budgetType: categoryTypes[2].id,
    value: "salary",
    caption: "Salary",
    color: "#173982",
  },
  {
    id: 15,
    expenseType: expenseTypes[1].id,
    budgetType: categoryTypes[2].id,
    value: "salary",
    caption: "Salary",
    color: "#5c7463",
  },
  {
    id: 16,
    expenseType: expenseTypes[1].id,
    budgetType: categoryTypes[2].id,
    value: "business",
    caption: "Business",
    color: "#fd9a7b",
  },
  {
    id: 17,
    expenseType: expenseTypes[1].id,
    budgetType: categoryTypes[2].id,
    value: "gifts",
    caption: "Gifts",
    color: "#cf6888",
  },
  {
    id: 18,
    expenseType: expenseTypes[1].id,
    budgetType: categoryTypes[2].id,
    value: "extraincome",
    caption: "Extra Income",
    color: "#badc95",
  },
  {
    id: 19,
    expenseType: expenseTypes[1].id,
    budgetType: categoryTypes[2].id,
    value: "other",
    caption: "Other",
    color: "#44444b",
  },
];
